// <auto-generated />
namespace HomePlanIt.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CommentedOut : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommentedOut));
        
        string IMigrationMetadata.Id
        {
            get { return "201812051442553_CommentedOut"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
